language: python
python:
  - "3.8"
# command to install dependencies
install:
  - pip install -r requirements.txt
cache:
  directories:
  - allure_reports
# command to run tests
script:
  - pytest --headless=true --alluredir=allure_reports
